typemedia_index:
    path:     /
    defaults: { _controller: "EniMediaBundle:TypeMedia:index" }
    methods:  GET

typemedia_show:
    path:     /{id}/show
    defaults: { _controller: "EniMediaBundle:TypeMedia:show" }
    methods:  GET

typemedia_new:
    path:     /new
    defaults: { _controller: "EniMediaBundle:TypeMedia:new" }
    methods:  [GET, POST]

typemedia_edit:
    path:     /{id}/edit
    defaults: { _controller: "EniMediaBundle:TypeMedia:edit" }
    methods:  [GET, POST]

typemedia_delete:
    path:     /{id}/delete
    defaults: { _controller: "EniMediaBundle:TypeMedia:delete" }
    methods:  DELETE
